// Code generated by protoc-gen-go. DO NOT EDIT.
// source: pb/grppt.proto

package pb

import (
	context "context"
	fmt "fmt"
	math "math"

	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Values struct {
	Values               []string `protobuf:"bytes,1,rep,name=values,proto3" json:"values,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Values) Reset()         { *m = Values{} }
func (m *Values) String() string { return proto.CompactTextString(m) }
func (*Values) ProtoMessage()    {}
func (*Values) Descriptor() ([]byte, []int) {
	return fileDescriptor_48a135b925a85794, []int{0}
}

func (m *Values) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Values.Unmarshal(m, b)
}
func (m *Values) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Values.Marshal(b, m, deterministic)
}
func (m *Values) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Values.Merge(m, src)
}
func (m *Values) XXX_Size() int {
	return xxx_messageInfo_Values.Size(m)
}
func (m *Values) XXX_DiscardUnknown() {
	xxx_messageInfo_Values.DiscardUnknown(m)
}

var xxx_messageInfo_Values proto.InternalMessageInfo

func (m *Values) GetValues() []string {
	if m != nil {
		return m.Values
	}
	return nil
}

type Request struct {
	Proto                string             `protobuf:"bytes,1,opt,name=proto,proto3" json:"proto,omitempty"`
	ProtoMajor           int32              `protobuf:"varint,2,opt,name=protoMajor,proto3" json:"protoMajor,omitempty"`
	ProtoMinor           int32              `protobuf:"varint,3,opt,name=protoMinor,proto3" json:"protoMinor,omitempty"`
	Method               string             `protobuf:"bytes,4,opt,name=method,proto3" json:"method,omitempty"`
	Url                  string             `protobuf:"bytes,5,opt,name=url,proto3" json:"url,omitempty"`
	Headers              map[string]*Values `protobuf:"bytes,6,rep,name=headers,proto3" json:"headers,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	Body                 []byte             `protobuf:"bytes,7,opt,name=body,proto3" json:"body,omitempty"`
	XXX_NoUnkeyedLiteral struct{}           `json:"-"`
	XXX_unrecognized     []byte             `json:"-"`
	XXX_sizecache        int32              `json:"-"`
}

func (m *Request) Reset()         { *m = Request{} }
func (m *Request) String() string { return proto.CompactTextString(m) }
func (*Request) ProtoMessage()    {}
func (*Request) Descriptor() ([]byte, []int) {
	return fileDescriptor_48a135b925a85794, []int{1}
}

func (m *Request) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Request.Unmarshal(m, b)
}
func (m *Request) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Request.Marshal(b, m, deterministic)
}
func (m *Request) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Request.Merge(m, src)
}
func (m *Request) XXX_Size() int {
	return xxx_messageInfo_Request.Size(m)
}
func (m *Request) XXX_DiscardUnknown() {
	xxx_messageInfo_Request.DiscardUnknown(m)
}

var xxx_messageInfo_Request proto.InternalMessageInfo

func (m *Request) GetProto() string {
	if m != nil {
		return m.Proto
	}
	return ""
}

func (m *Request) GetProtoMajor() int32 {
	if m != nil {
		return m.ProtoMajor
	}
	return 0
}

func (m *Request) GetProtoMinor() int32 {
	if m != nil {
		return m.ProtoMinor
	}
	return 0
}

func (m *Request) GetMethod() string {
	if m != nil {
		return m.Method
	}
	return ""
}

func (m *Request) GetUrl() string {
	if m != nil {
		return m.Url
	}
	return ""
}

func (m *Request) GetHeaders() map[string]*Values {
	if m != nil {
		return m.Headers
	}
	return nil
}

func (m *Request) GetBody() []byte {
	if m != nil {
		return m.Body
	}
	return nil
}

type Response struct {
	Proto                string             `protobuf:"bytes,1,opt,name=proto,proto3" json:"proto,omitempty"`
	ProtoMajor           int32              `protobuf:"varint,2,opt,name=protoMajor,proto3" json:"protoMajor,omitempty"`
	ProtoMinor           int32              `protobuf:"varint,3,opt,name=protoMinor,proto3" json:"protoMinor,omitempty"`
	StatusCode           int32              `protobuf:"varint,4,opt,name=statusCode,proto3" json:"statusCode,omitempty"`
	ReasonPhase          string             `protobuf:"bytes,5,opt,name=reasonPhase,proto3" json:"reasonPhase,omitempty"`
	Headers              map[string]*Values `protobuf:"bytes,6,rep,name=headers,proto3" json:"headers,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	Body                 []byte             `protobuf:"bytes,7,opt,name=body,proto3" json:"body,omitempty"`
	XXX_NoUnkeyedLiteral struct{}           `json:"-"`
	XXX_unrecognized     []byte             `json:"-"`
	XXX_sizecache        int32              `json:"-"`
}

func (m *Response) Reset()         { *m = Response{} }
func (m *Response) String() string { return proto.CompactTextString(m) }
func (*Response) ProtoMessage()    {}
func (*Response) Descriptor() ([]byte, []int) {
	return fileDescriptor_48a135b925a85794, []int{2}
}

func (m *Response) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Response.Unmarshal(m, b)
}
func (m *Response) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Response.Marshal(b, m, deterministic)
}
func (m *Response) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Response.Merge(m, src)
}
func (m *Response) XXX_Size() int {
	return xxx_messageInfo_Response.Size(m)
}
func (m *Response) XXX_DiscardUnknown() {
	xxx_messageInfo_Response.DiscardUnknown(m)
}

var xxx_messageInfo_Response proto.InternalMessageInfo

func (m *Response) GetProto() string {
	if m != nil {
		return m.Proto
	}
	return ""
}

func (m *Response) GetProtoMajor() int32 {
	if m != nil {
		return m.ProtoMajor
	}
	return 0
}

func (m *Response) GetProtoMinor() int32 {
	if m != nil {
		return m.ProtoMinor
	}
	return 0
}

func (m *Response) GetStatusCode() int32 {
	if m != nil {
		return m.StatusCode
	}
	return 0
}

func (m *Response) GetReasonPhase() string {
	if m != nil {
		return m.ReasonPhase
	}
	return ""
}

func (m *Response) GetHeaders() map[string]*Values {
	if m != nil {
		return m.Headers
	}
	return nil
}

func (m *Response) GetBody() []byte {
	if m != nil {
		return m.Body
	}
	return nil
}

func init() {
	proto.RegisterType((*Values)(nil), "pb.Values")
	proto.RegisterType((*Request)(nil), "pb.Request")
	proto.RegisterMapType((map[string]*Values)(nil), "pb.Request.HeadersEntry")
	proto.RegisterType((*Response)(nil), "pb.Response")
	proto.RegisterMapType((map[string]*Values)(nil), "pb.Response.HeadersEntry")
}

func init() { proto.RegisterFile("pb/grppt.proto", fileDescriptor_48a135b925a85794) }

var fileDescriptor_48a135b925a85794 = []byte{
	// 357 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xbc, 0x92, 0xcf, 0x6a, 0xdb, 0x40,
	0x10, 0xc6, 0xbb, 0x92, 0x25, 0xdb, 0x23, 0x51, 0xca, 0x52, 0xca, 0xd6, 0x07, 0xb3, 0xd5, 0x49,
	0x50, 0x50, 0x8b, 0x7c, 0x29, 0x3d, 0xb6, 0xce, 0x9f, 0x4b, 0x20, 0xac, 0x21, 0x87, 0x1c, 0x02,
	0x52, 0x34, 0xc4, 0x4e, 0x6c, 0xed, 0x66, 0x77, 0x65, 0xf0, 0xa3, 0xe4, 0x39, 0xf2, 0x82, 0x41,
	0x2b, 0x85, 0x88, 0x1c, 0x72, 0x4b, 0x6e, 0xdf, 0x7c, 0xdf, 0x48, 0x33, 0xf3, 0x93, 0xe0, 0xb3,
	0x2a, 0x7f, 0xdd, 0x68, 0xa5, 0x6c, 0xa6, 0xb4, 0xb4, 0x92, 0x7a, 0xaa, 0x4c, 0x38, 0x84, 0x17,
	0xc5, 0xb6, 0x41, 0x43, 0xbf, 0x41, 0xb8, 0x77, 0x8a, 0x11, 0xee, 0xa7, 0x53, 0xd1, 0x57, 0xc9,
	0x83, 0x07, 0x63, 0x81, 0xf7, 0x0d, 0x1a, 0x4b, 0xbf, 0x42, 0xe0, 0x1e, 0x65, 0x84, 0x93, 0x74,
	0x2a, 0xba, 0x82, 0xce, 0x01, 0x9c, 0x38, 0x2b, 0x6e, 0xa5, 0x66, 0x1e, 0x27, 0x69, 0x20, 0x06,
	0xce, 0x4b, 0xbe, 0xa9, 0xa5, 0x66, 0xfe, 0x30, 0x6f, 0x9d, 0x76, 0xf2, 0x0e, 0xed, 0x5a, 0x56,
	0x6c, 0xe4, 0x5e, 0xdb, 0x57, 0xf4, 0x0b, 0xf8, 0x8d, 0xde, 0xb2, 0xc0, 0x99, 0xad, 0xa4, 0x39,
	0x8c, 0xd7, 0x58, 0x54, 0xa8, 0x0d, 0x0b, 0xb9, 0x9f, 0x46, 0x39, 0xcb, 0x54, 0x99, 0xf5, 0xdb,
	0x65, 0xa7, 0x5d, 0x74, 0x54, 0x5b, 0x7d, 0x10, 0xcf, 0x8d, 0x94, 0xc2, 0xa8, 0x94, 0xd5, 0x81,
	0x8d, 0x39, 0x49, 0x63, 0xe1, 0xf4, 0xec, 0x18, 0xe2, 0x61, 0x73, 0x3b, 0xe9, 0x0e, 0x0f, 0xfd,
	0x55, 0xad, 0xa4, 0x1c, 0x02, 0x77, 0xbf, 0x3b, 0x27, 0xca, 0xa1, 0x9d, 0xd3, 0x81, 0x12, 0x5d,
	0xf0, 0xd7, 0xfb, 0x43, 0x92, 0x47, 0x0f, 0x26, 0x02, 0x8d, 0x92, 0xb5, 0xc1, 0x77, 0x82, 0x33,
	0x07, 0x30, 0xb6, 0xb0, 0x8d, 0xf9, 0x2f, 0x2b, 0x74, 0x80, 0x02, 0x31, 0x70, 0x28, 0x87, 0x48,
	0x63, 0x61, 0x64, 0x7d, 0xbe, 0x2e, 0x0c, 0xf6, 0xb0, 0x86, 0x16, 0x5d, 0xbc, 0x86, 0xf6, 0xbd,
	0x83, 0xd6, 0xad, 0xfd, 0xf1, 0xd4, 0xf2, 0x2b, 0x88, 0x4f, 0xda, 0xdf, 0x70, 0x85, 0x7a, 0xbf,
	0xb9, 0x46, 0xfa, 0x03, 0xbc, 0xa5, 0xa4, 0xd1, 0xe0, 0x53, 0xce, 0xe2, 0xe1, 0x8a, 0xc9, 0x27,
	0xfa, 0x13, 0x26, 0x4b, 0xb9, 0xb2, 0x1a, 0x8b, 0xdd, 0x9b, 0x8d, 0x29, 0xf9, 0x4d, 0xfe, 0x8d,
	0x2e, 0x3d, 0x55, 0x96, 0xa1, 0x83, 0xb8, 0x78, 0x0a, 0x00, 0x00, 0xff, 0xff, 0x1e, 0xd6, 0x2a,
	0x90, 0xf6, 0x02, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// GrpptServiceClient is the client API for GrpptService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type GrpptServiceClient interface {
	Do(ctx context.Context, in *Request, opts ...grpc.CallOption) (*Response, error)
	DoStream(ctx context.Context, opts ...grpc.CallOption) (GrpptService_DoStreamClient, error)
}

type grpptServiceClient struct {
	cc *grpc.ClientConn
}

func NewGrpptServiceClient(cc *grpc.ClientConn) GrpptServiceClient {
	return &grpptServiceClient{cc}
}

func (c *grpptServiceClient) Do(ctx context.Context, in *Request, opts ...grpc.CallOption) (*Response, error) {
	out := new(Response)
	err := c.cc.Invoke(ctx, "/pb.GrpptService/Do", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *grpptServiceClient) DoStream(ctx context.Context, opts ...grpc.CallOption) (GrpptService_DoStreamClient, error) {
	stream, err := c.cc.NewStream(ctx, &_GrpptService_serviceDesc.Streams[0], "/pb.GrpptService/DoStream", opts...)
	if err != nil {
		return nil, err
	}
	x := &grpptServiceDoStreamClient{stream}
	return x, nil
}

type GrpptService_DoStreamClient interface {
	Send(*Request) error
	Recv() (*Response, error)
	grpc.ClientStream
}

type grpptServiceDoStreamClient struct {
	grpc.ClientStream
}

func (x *grpptServiceDoStreamClient) Send(m *Request) error {
	return x.ClientStream.SendMsg(m)
}

func (x *grpptServiceDoStreamClient) Recv() (*Response, error) {
	m := new(Response)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// GrpptServiceServer is the service API for GrpptService service.
type GrpptServiceServer interface {
	Do(context.Context, *Request) (*Response, error)
	DoStream(GrpptService_DoStreamServer) error
}

// UnimplementedGrpptServiceServer can be embedded to have forward compatible implementations.
type UnimplementedGrpptServiceServer struct {
}

func (*UnimplementedGrpptServiceServer) Do(ctx context.Context, req *Request) (*Response, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Do not implemented")
}
func (*UnimplementedGrpptServiceServer) DoStream(srv GrpptService_DoStreamServer) error {
	return status.Errorf(codes.Unimplemented, "method DoStream not implemented")
}

func RegisterGrpptServiceServer(s *grpc.Server, srv GrpptServiceServer) {
	s.RegisterService(&_GrpptService_serviceDesc, srv)
}

func _GrpptService_Do_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Request)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GrpptServiceServer).Do(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.GrpptService/Do",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GrpptServiceServer).Do(ctx, req.(*Request))
	}
	return interceptor(ctx, in, info, handler)
}

func _GrpptService_DoStream_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(GrpptServiceServer).DoStream(&grpptServiceDoStreamServer{stream})
}

type GrpptService_DoStreamServer interface {
	Send(*Response) error
	Recv() (*Request, error)
	grpc.ServerStream
}

type grpptServiceDoStreamServer struct {
	grpc.ServerStream
}

func (x *grpptServiceDoStreamServer) Send(m *Response) error {
	return x.ServerStream.SendMsg(m)
}

func (x *grpptServiceDoStreamServer) Recv() (*Request, error) {
	m := new(Request)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

var _GrpptService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "pb.GrpptService",
	HandlerType: (*GrpptServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Do",
			Handler:    _GrpptService_Do_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "DoStream",
			Handler:       _GrpptService_DoStream_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "pb/grppt.proto",
}
