// Code generated by protoc-gen-go. DO NOT EDIT.
// source: pb/grppt.proto

package pb

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Values struct {
	Values               []string `protobuf:"bytes,1,rep,name=values,proto3" json:"values,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Values) Reset()         { *m = Values{} }
func (m *Values) String() string { return proto.CompactTextString(m) }
func (*Values) ProtoMessage()    {}
func (*Values) Descriptor() ([]byte, []int) {
	return fileDescriptor_48a135b925a85794, []int{0}
}

func (m *Values) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Values.Unmarshal(m, b)
}
func (m *Values) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Values.Marshal(b, m, deterministic)
}
func (m *Values) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Values.Merge(m, src)
}
func (m *Values) XXX_Size() int {
	return xxx_messageInfo_Values.Size(m)
}
func (m *Values) XXX_DiscardUnknown() {
	xxx_messageInfo_Values.DiscardUnknown(m)
}

var xxx_messageInfo_Values proto.InternalMessageInfo

func (m *Values) GetValues() []string {
	if m != nil {
		return m.Values
	}
	return nil
}

type Request struct {
	Proto                string             `protobuf:"bytes,1,opt,name=proto,proto3" json:"proto,omitempty"`
	ProtoMajor           int32              `protobuf:"varint,2,opt,name=protoMajor,proto3" json:"protoMajor,omitempty"`
	ProtoMinor           int32              `protobuf:"varint,3,opt,name=protoMinor,proto3" json:"protoMinor,omitempty"`
	Method               string             `protobuf:"bytes,4,opt,name=method,proto3" json:"method,omitempty"`
	Url                  string             `protobuf:"bytes,5,opt,name=url,proto3" json:"url,omitempty"`
	Headers              map[string]*Values `protobuf:"bytes,6,rep,name=headers,proto3" json:"headers,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	Body                 []byte             `protobuf:"bytes,7,opt,name=body,proto3" json:"body,omitempty"`
	XXX_NoUnkeyedLiteral struct{}           `json:"-"`
	XXX_unrecognized     []byte             `json:"-"`
	XXX_sizecache        int32              `json:"-"`
}

func (m *Request) Reset()         { *m = Request{} }
func (m *Request) String() string { return proto.CompactTextString(m) }
func (*Request) ProtoMessage()    {}
func (*Request) Descriptor() ([]byte, []int) {
	return fileDescriptor_48a135b925a85794, []int{1}
}

func (m *Request) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Request.Unmarshal(m, b)
}
func (m *Request) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Request.Marshal(b, m, deterministic)
}
func (m *Request) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Request.Merge(m, src)
}
func (m *Request) XXX_Size() int {
	return xxx_messageInfo_Request.Size(m)
}
func (m *Request) XXX_DiscardUnknown() {
	xxx_messageInfo_Request.DiscardUnknown(m)
}

var xxx_messageInfo_Request proto.InternalMessageInfo

func (m *Request) GetProto() string {
	if m != nil {
		return m.Proto
	}
	return ""
}

func (m *Request) GetProtoMajor() int32 {
	if m != nil {
		return m.ProtoMajor
	}
	return 0
}

func (m *Request) GetProtoMinor() int32 {
	if m != nil {
		return m.ProtoMinor
	}
	return 0
}

func (m *Request) GetMethod() string {
	if m != nil {
		return m.Method
	}
	return ""
}

func (m *Request) GetUrl() string {
	if m != nil {
		return m.Url
	}
	return ""
}

func (m *Request) GetHeaders() map[string]*Values {
	if m != nil {
		return m.Headers
	}
	return nil
}

func (m *Request) GetBody() []byte {
	if m != nil {
		return m.Body
	}
	return nil
}

type Response struct {
	Proto                string             `protobuf:"bytes,1,opt,name=proto,proto3" json:"proto,omitempty"`
	ProtoMajor           int32              `protobuf:"varint,2,opt,name=protoMajor,proto3" json:"protoMajor,omitempty"`
	ProtoMinor           int32              `protobuf:"varint,3,opt,name=protoMinor,proto3" json:"protoMinor,omitempty"`
	StatusCode           int32              `protobuf:"varint,4,opt,name=statusCode,proto3" json:"statusCode,omitempty"`
	ReasonPhase          string             `protobuf:"bytes,5,opt,name=reasonPhase,proto3" json:"reasonPhase,omitempty"`
	Headers              map[string]*Values `protobuf:"bytes,6,rep,name=headers,proto3" json:"headers,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	Body                 []byte             `protobuf:"bytes,7,opt,name=body,proto3" json:"body,omitempty"`
	XXX_NoUnkeyedLiteral struct{}           `json:"-"`
	XXX_unrecognized     []byte             `json:"-"`
	XXX_sizecache        int32              `json:"-"`
}

func (m *Response) Reset()         { *m = Response{} }
func (m *Response) String() string { return proto.CompactTextString(m) }
func (*Response) ProtoMessage()    {}
func (*Response) Descriptor() ([]byte, []int) {
	return fileDescriptor_48a135b925a85794, []int{2}
}

func (m *Response) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Response.Unmarshal(m, b)
}
func (m *Response) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Response.Marshal(b, m, deterministic)
}
func (m *Response) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Response.Merge(m, src)
}
func (m *Response) XXX_Size() int {
	return xxx_messageInfo_Response.Size(m)
}
func (m *Response) XXX_DiscardUnknown() {
	xxx_messageInfo_Response.DiscardUnknown(m)
}

var xxx_messageInfo_Response proto.InternalMessageInfo

func (m *Response) GetProto() string {
	if m != nil {
		return m.Proto
	}
	return ""
}

func (m *Response) GetProtoMajor() int32 {
	if m != nil {
		return m.ProtoMajor
	}
	return 0
}

func (m *Response) GetProtoMinor() int32 {
	if m != nil {
		return m.ProtoMinor
	}
	return 0
}

func (m *Response) GetStatusCode() int32 {
	if m != nil {
		return m.StatusCode
	}
	return 0
}

func (m *Response) GetReasonPhase() string {
	if m != nil {
		return m.ReasonPhase
	}
	return ""
}

func (m *Response) GetHeaders() map[string]*Values {
	if m != nil {
		return m.Headers
	}
	return nil
}

func (m *Response) GetBody() []byte {
	if m != nil {
		return m.Body
	}
	return nil
}

func init() {
	proto.RegisterType((*Values)(nil), "pb.Values")
	proto.RegisterType((*Request)(nil), "pb.Request")
	proto.RegisterMapType((map[string]*Values)(nil), "pb.Request.HeadersEntry")
	proto.RegisterType((*Response)(nil), "pb.Response")
	proto.RegisterMapType((map[string]*Values)(nil), "pb.Response.HeadersEntry")
}

func init() { proto.RegisterFile("pb/grppt.proto", fileDescriptor_48a135b925a85794) }

var fileDescriptor_48a135b925a85794 = []byte{
	// 334 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xbc, 0x92, 0xcf, 0x4e, 0x83, 0x40,
	0x10, 0xc6, 0x05, 0x0a, 0xb5, 0x03, 0x31, 0x66, 0x63, 0xcc, 0xda, 0x43, 0xb3, 0x72, 0xe2, 0x84,
	0x91, 0x5e, 0x8c, 0x47, 0xff, 0x5f, 0x4c, 0xcc, 0x9a, 0x78, 0xf0, 0x06, 0x32, 0xb1, 0xd5, 0xca,
	0xae, 0xbb, 0xd0, 0xa4, 0x8f, 0xe2, 0x73, 0xf8, 0x82, 0x66, 0x17, 0x8c, 0x1b, 0xef, 0x7a, 0xfb,
	0xe6, 0xfb, 0x06, 0x66, 0xe6, 0x07, 0xb0, 0x23, 0xab, 0xa3, 0x67, 0x25, 0x65, 0x9b, 0x4b, 0x25,
	0x5a, 0x41, 0x7c, 0x59, 0xa5, 0x0c, 0xa2, 0x87, 0x72, 0xd5, 0xa1, 0x26, 0xfb, 0x10, 0xad, 0xad,
	0xa2, 0x1e, 0x0b, 0xb2, 0x09, 0x1f, 0xaa, 0xf4, 0xc3, 0x87, 0x31, 0xc7, 0xf7, 0x0e, 0x75, 0x4b,
	0xf6, 0x20, 0xb4, 0x8f, 0x52, 0x8f, 0x79, 0xd9, 0x84, 0xf7, 0x05, 0x99, 0x01, 0x58, 0x71, 0x5b,
	0xbe, 0x08, 0x45, 0x7d, 0xe6, 0x65, 0x21, 0x77, 0x9c, 0x9f, 0x7c, 0xd9, 0x08, 0x45, 0x03, 0x37,
	0x37, 0x8e, 0x99, 0xfc, 0x86, 0xed, 0x42, 0xd4, 0x74, 0x64, 0x5f, 0x3b, 0x54, 0x64, 0x17, 0x82,
	0x4e, 0xad, 0x68, 0x68, 0x4d, 0x23, 0x49, 0x01, 0xe3, 0x05, 0x96, 0x35, 0x2a, 0x4d, 0x23, 0x16,
	0x64, 0x71, 0x41, 0x73, 0x59, 0xe5, 0xc3, 0x76, 0xf9, 0x4d, 0x1f, 0x5d, 0x36, 0xad, 0xda, 0xf0,
	0xef, 0x46, 0x42, 0x60, 0x54, 0x89, 0x7a, 0x43, 0xc7, 0xcc, 0xcb, 0x12, 0x6e, 0xf5, 0xf4, 0x0a,
	0x12, 0xb7, 0xd9, 0x4c, 0x7a, 0xc5, 0xcd, 0x70, 0x95, 0x91, 0x84, 0x41, 0x68, 0xef, 0xb7, 0xe7,
	0xc4, 0x05, 0x98, 0x39, 0x3d, 0x28, 0xde, 0x07, 0xa7, 0xfe, 0x89, 0x97, 0x7e, 0xfa, 0xb0, 0xcd,
	0x51, 0x4b, 0xd1, 0x68, 0xfc, 0x23, 0x38, 0x33, 0x00, 0xdd, 0x96, 0x6d, 0xa7, 0xcf, 0x45, 0x8d,
	0x16, 0x50, 0xc8, 0x1d, 0x87, 0x30, 0x88, 0x15, 0x96, 0x5a, 0x34, 0x77, 0x8b, 0x52, 0xe3, 0x00,
	0xcb, 0xb5, 0xc8, 0xfc, 0x37, 0xb4, 0x83, 0x1e, 0x5a, 0xbf, 0xf6, 0xff, 0x53, 0x2b, 0x8e, 0x21,
	0xb9, 0x36, 0xbf, 0xe1, 0x3d, 0xaa, 0xf5, 0xf2, 0x09, 0xc9, 0x21, 0xf8, 0x17, 0x82, 0xc4, 0xce,
	0xa7, 0x9c, 0x26, 0xee, 0x8a, 0xe9, 0xd6, 0xd9, 0xe8, 0xd1, 0x97, 0x55, 0x15, 0x59, 0x2e, 0xf3,
	0xaf, 0x00, 0x00, 0x00, 0xff, 0xff, 0x7f, 0xc8, 0xac, 0xc9, 0xc9, 0x02, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// GrpptServiceClient is the client API for GrpptService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type GrpptServiceClient interface {
	Do(ctx context.Context, in *Request, opts ...grpc.CallOption) (*Response, error)
}

type grpptServiceClient struct {
	cc *grpc.ClientConn
}

func NewGrpptServiceClient(cc *grpc.ClientConn) GrpptServiceClient {
	return &grpptServiceClient{cc}
}

func (c *grpptServiceClient) Do(ctx context.Context, in *Request, opts ...grpc.CallOption) (*Response, error) {
	out := new(Response)
	err := c.cc.Invoke(ctx, "/pb.GrpptService/Do", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// GrpptServiceServer is the server API for GrpptService service.
type GrpptServiceServer interface {
	Do(context.Context, *Request) (*Response, error)
}

// UnimplementedGrpptServiceServer can be embedded to have forward compatible implementations.
type UnimplementedGrpptServiceServer struct {
}

func (*UnimplementedGrpptServiceServer) Do(ctx context.Context, req *Request) (*Response, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Do not implemented")
}

func RegisterGrpptServiceServer(s *grpc.Server, srv GrpptServiceServer) {
	s.RegisterService(&_GrpptService_serviceDesc, srv)
}

func _GrpptService_Do_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Request)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GrpptServiceServer).Do(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.GrpptService/Do",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GrpptServiceServer).Do(ctx, req.(*Request))
	}
	return interceptor(ctx, in, info, handler)
}

var _GrpptService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "pb.GrpptService",
	HandlerType: (*GrpptServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Do",
			Handler:    _GrpptService_Do_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "pb/grppt.proto",
}
